// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yoadmlaonphszaptztqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvYWRtbGFvbnBoc3phcHR6dHF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwODQ3MzUsImV4cCI6MjA1ODY2MDczNX0.SAd-oeLe7otSwnQmcgUjD75iaKbjOsEpTFNVe16JITU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);